#############################################################################
# Makefile for building: Vector\ Visualizer.app/Contents/MacOS/Vector\ Visualizer
# Generated by qmake (3.1) (Qt 6.0.2)
# Project:  Vector Visualizer.pro
# Template: app
# Command: /Users/KKjeer/Qt/6.0.2/clang_64/bin/qmake -o Makefile Vector\ Visualizer.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_OPENGLWIDGETS_LIB -DQT_WIDGETS_LIB -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk -mmacosx-version-min=10.14 -Wall -Wextra -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk -mmacosx-version-min=10.14 -Wall -Wextra -fPIC $(DEFINES)
INCPATH       = -I. -I. -I../../../../Qt/6.0.2/clang_64/lib/QtOpenGLWidgets.framework/Headers -I../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers -I../../../../Qt/6.0.2/clang_64/lib/QtOpenGL.framework/Headers -I../../../../Qt/6.0.2/clang_64/lib/QtGui.framework/Headers -I../../../../Qt/6.0.2/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/System/Library/Frameworks/AGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/System/Library/Frameworks/AGL.framework/Headers -I../../../../Qt/6.0.2/clang_64/mkspecs/macx-clang -F/Users/KKjeer/Qt/6.0.2/clang_64/lib
QMAKE         = /Users/KKjeer/Qt/6.0.2/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/KKjeer/Qt/6.0.2/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/KKjeer/Qt/6.0.2/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Vector\ Visualizer1.0.0
DISTDIR = /Users/KKjeer/Documents/Coding/Qt/Vector\ Visualizer/.tmp/Vector\ Visualizer1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk -mmacosx-version-min=10.14 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/Users/KKjeer/Qt/6.0.2/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/KKjeer/Qt/6.0.2/clang_64/lib -framework QtOpenGLWidgets -framework QtWidgets -framework QtOpenGL -framework QtGui -framework AppKit -framework ImageIO -framework Metal -framework QtCore -framework DiskArbitration -framework IOKit -framework AGL -framework OpenGL -framework GLUT 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Expr.cpp \
		main.cpp \
		mainwidget.cpp \
		Utils/MathUtils.cpp \
		oglwidget.cpp \
		Parsing/Parser.cpp \
		Parsing/ParserAlt.cpp \
		Parsing/Lexer.cpp \
		Utils/StringUtils.cpp \
		VectorField.cpp \
		Graphics/Number.cpp moc_mainwidget.cpp
OBJECTS       = Expr.o \
		main.o \
		mainwidget.o \
		MathUtils.o \
		oglwidget.o \
		Parser.o \
		ParserAlt.o \
		Lexer.o \
		StringUtils.o \
		VectorField.o \
		Number.o \
		moc_mainwidget.o
DIST          = ../../../../Qt/6.0.2/clang_64/mkspecs/features/spec_pre.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/device_config.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/common/unix.conf \
		../../../../Qt/6.0.2/clang_64/mkspecs/common/mac.conf \
		../../../../Qt/6.0.2/clang_64/mkspecs/common/macx.conf \
		../../../../Qt/6.0.2/clang_64/mkspecs/common/sanitize.conf \
		../../../../Qt/6.0.2/clang_64/mkspecs/common/gcc-base.conf \
		../../../../Qt/6.0.2/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../../Qt/6.0.2/clang_64/mkspecs/common/clang.conf \
		../../../../Qt/6.0.2/clang_64/mkspecs/common/clang-mac.conf \
		../../../../Qt/6.0.2/clang_64/mkspecs/qconfig.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_ext_freetype.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_ext_libpng.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_core_qobject_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_linguist.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_linguist_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_openglwidgets.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_svgwidgets.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_tools_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/qt_functions.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/qt_config.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/toolchain.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/mac/toolchain.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/default_pre.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/resolve_config.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/default_post.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/mac/mac.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/warn_on.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/qt.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/resources_functions.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/resources.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/moc.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/unix/opengl.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/uic.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/unix/thread.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/qmake_use.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/file_copies.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/mac/rez.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/exceptions.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/yacc.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/lex.prf \
		Vector Visualizer.pro Expr.h \
		mainwidget.h \
		Utils/MathUtils.h \
		oglwidget.h \
		Parsing/Parser.h \
		Parsing/ParserAlt.h \
		Parsing/Lexer.h \
		Utils/StringUtils.h \
		VectorField.h \
		Graphics/Number.h Expr.cpp \
		main.cpp \
		mainwidget.cpp \
		Utils/MathUtils.cpp \
		oglwidget.cpp \
		Parsing/Parser.cpp \
		Parsing/ParserAlt.cpp \
		Parsing/Lexer.cpp \
		Utils/StringUtils.cpp \
		VectorField.cpp \
		Graphics/Number.cpp
QMAKE_TARGET  = Vector\ Visualizer
DESTDIR       = 
TARGET        = Vector\ Visualizer.app/Contents/MacOS/Vector\ Visualizer

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 11.3
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Applications/Xcode.app/Contents/Developer
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/KKjeer/Documents/Coding/Qt/Vector Visualizer/Vector Visualizer.pro


include /Users/KKjeer/Qt/6.0.2/clang_64/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

Vector\ Visualizer.app/Contents/MacOS/Vector\ Visualizer:  $(OBJECTS)  
	@test -d Vector\ Visualizer.app/Contents/MacOS/ || mkdir -p Vector\ Visualizer.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Vector\ Visualizer.pro ../../../../Qt/6.0.2/clang_64/mkspecs/macx-clang/qmake.conf ../../../../Qt/6.0.2/clang_64/mkspecs/features/spec_pre.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/device_config.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/common/unix.conf \
		../../../../Qt/6.0.2/clang_64/mkspecs/common/mac.conf \
		../../../../Qt/6.0.2/clang_64/mkspecs/common/macx.conf \
		../../../../Qt/6.0.2/clang_64/mkspecs/common/sanitize.conf \
		../../../../Qt/6.0.2/clang_64/mkspecs/common/gcc-base.conf \
		../../../../Qt/6.0.2/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../../Qt/6.0.2/clang_64/mkspecs/common/clang.conf \
		../../../../Qt/6.0.2/clang_64/mkspecs/common/clang-mac.conf \
		../../../../Qt/6.0.2/clang_64/mkspecs/qconfig.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_ext_freetype.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_ext_libpng.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_core_qobject_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_linguist.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_linguist_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_openglwidgets.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_svgwidgets.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_tools_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/qt_functions.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/qt_config.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/toolchain.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/mac/toolchain.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/default_pre.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/resolve_config.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/default_post.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/mac/mac.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/warn_on.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/qt.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/resources_functions.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/resources.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/moc.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/unix/opengl.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/uic.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/unix/thread.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/qmake_use.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/file_copies.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/mac/rez.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/exceptions.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/yacc.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/lex.prf \
		Vector\ Visualizer.pro \
		../../../../Qt/6.0.2/clang_64/lib/QtOpenGLWidgets.framework/Resources/QtOpenGLWidgets.prl \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		../../../../Qt/6.0.2/clang_64/lib/QtOpenGL.framework/Resources/QtOpenGL.prl \
		../../../../Qt/6.0.2/clang_64/lib/QtGui.framework/Resources/QtGui.prl \
		../../../../Qt/6.0.2/clang_64/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile Vector\ Visualizer.pro
../../../../Qt/6.0.2/clang_64/mkspecs/features/spec_pre.prf:
../../../../Qt/6.0.2/clang_64/mkspecs/features/device_config.prf:
../../../../Qt/6.0.2/clang_64/mkspecs/common/unix.conf:
../../../../Qt/6.0.2/clang_64/mkspecs/common/mac.conf:
../../../../Qt/6.0.2/clang_64/mkspecs/common/macx.conf:
../../../../Qt/6.0.2/clang_64/mkspecs/common/sanitize.conf:
../../../../Qt/6.0.2/clang_64/mkspecs/common/gcc-base.conf:
../../../../Qt/6.0.2/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../../Qt/6.0.2/clang_64/mkspecs/common/clang.conf:
../../../../Qt/6.0.2/clang_64/mkspecs/common/clang-mac.conf:
../../../../Qt/6.0.2/clang_64/mkspecs/qconfig.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_ext_freetype.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_ext_libpng.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_core_qobject_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_linguist.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_linguist_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_openglwidgets.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_openglwidgets_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_qmlmodels.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_svgwidgets.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_svgwidgets_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_tools_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/features/qt_functions.prf:
../../../../Qt/6.0.2/clang_64/mkspecs/features/qt_config.prf:
../../../../Qt/6.0.2/clang_64/mkspecs/macx-clang/qmake.conf:
../../../../Qt/6.0.2/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../../Qt/6.0.2/clang_64/mkspecs/features/exclusive_builds.prf:
../../../../Qt/6.0.2/clang_64/mkspecs/features/mac/sdk.prf:
../../../../Qt/6.0.2/clang_64/mkspecs/features/toolchain.prf:
../../../../Qt/6.0.2/clang_64/mkspecs/features/mac/toolchain.prf:
../../../../Qt/6.0.2/clang_64/mkspecs/features/default_pre.prf:
../../../../Qt/6.0.2/clang_64/mkspecs/features/mac/default_pre.prf:
../../../../Qt/6.0.2/clang_64/mkspecs/features/resolve_config.prf:
../../../../Qt/6.0.2/clang_64/mkspecs/features/default_post.prf:
../../../../Qt/6.0.2/clang_64/mkspecs/features/mac/default_post.prf:
../../../../Qt/6.0.2/clang_64/mkspecs/features/mac/objective_c.prf:
../../../../Qt/6.0.2/clang_64/mkspecs/features/mac/mac.prf:
../../../../Qt/6.0.2/clang_64/mkspecs/features/warn_on.prf:
../../../../Qt/6.0.2/clang_64/mkspecs/features/qt.prf:
../../../../Qt/6.0.2/clang_64/mkspecs/features/resources_functions.prf:
../../../../Qt/6.0.2/clang_64/mkspecs/features/resources.prf:
../../../../Qt/6.0.2/clang_64/mkspecs/features/moc.prf:
../../../../Qt/6.0.2/clang_64/mkspecs/features/unix/opengl.prf:
../../../../Qt/6.0.2/clang_64/mkspecs/features/uic.prf:
../../../../Qt/6.0.2/clang_64/mkspecs/features/unix/thread.prf:
../../../../Qt/6.0.2/clang_64/mkspecs/features/qmake_use.prf:
../../../../Qt/6.0.2/clang_64/mkspecs/features/file_copies.prf:
../../../../Qt/6.0.2/clang_64/mkspecs/features/mac/rez.prf:
../../../../Qt/6.0.2/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../../../../Qt/6.0.2/clang_64/mkspecs/features/testcase_targets.prf:
../../../../Qt/6.0.2/clang_64/mkspecs/features/exceptions.prf:
../../../../Qt/6.0.2/clang_64/mkspecs/features/yacc.prf:
../../../../Qt/6.0.2/clang_64/mkspecs/features/lex.prf:
Vector\ Visualizer.pro:
../../../../Qt/6.0.2/clang_64/lib/QtOpenGLWidgets.framework/Resources/QtOpenGLWidgets.prl:
../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Resources/QtWidgets.prl:
../../../../Qt/6.0.2/clang_64/lib/QtOpenGL.framework/Resources/QtOpenGL.prl:
../../../../Qt/6.0.2/clang_64/lib/QtGui.framework/Resources/QtGui.prl:
../../../../Qt/6.0.2/clang_64/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Vector\ Visualizer.pro

qmake_all: FORCE

Vector\ Visualizer.app/Contents/PkgInfo: 
	@test -d Vector\ Visualizer.app/Contents || mkdir -p Vector\ Visualizer.app/Contents
	@$(DEL_FILE) Vector\ Visualizer.app/Contents/PkgInfo
	@echo "APPL????" > Vector\ Visualizer.app/Contents/PkgInfo
Vector\ Visualizer.app/Contents/Resources/empty.lproj: 
	@test -d Vector\ Visualizer.app/Contents/Resources || mkdir -p Vector\ Visualizer.app/Contents/Resources
	@touch Vector\ Visualizer.app/Contents/Resources/empty.lproj
	
Vector\ Visualizer.app/Contents/Info.plist: 
	@test -d Vector\ Visualizer.app/Contents || mkdir -p Vector\ Visualizer.app/Contents
	@$(DEL_FILE) Vector\ Visualizer.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,com.example.Vector-Visualizer,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},com.example.Vector-Visualizer,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.14,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,\$${IOS_LAUNCH_SCREEN},LaunchScreen,g" -e "s,@ICON@,isad.icns,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},isad.icns,g" -e "s,@EXECUTABLE@,Vector Visualizer,g" -e "s,@LIBRARY@,Vector Visualizer,g" -e "s,\$${EXECUTABLE_NAME},Vector Visualizer,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" ../../../../Qt/6.0.2/clang_64/mkspecs/macx-clang/Info.plist.app >Vector\ Visualizer.app/Contents/Info.plist
Vector\ Visualizer.app/Contents/Resources/isad.icns: isad.icns
	@test -d Vector\ Visualizer.app/Contents/Resources/ || mkdir -p Vector\ Visualizer.app/Contents/Resources/
	@$(DEL_FILE) Vector\ Visualizer.app/Contents/Resources/isad.icns
	@$(COPY_FILE) isad.icns Vector\ Visualizer.app/Contents/Resources/isad.icns

all: Makefile \
		Vector\ Visualizer.app/Contents/PkgInfo \
		Vector\ Visualizer.app/Contents/Resources/empty.lproj \
		Vector\ Visualizer.app/Contents/Info.plist \
		Vector\ Visualizer.app/Contents/Resources/isad.icns Vector\ Visualizer.app/Contents/MacOS/Vector\ Visualizer

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../../../Qt/6.0.2/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents Expr.h mainwidget.h Utils/MathUtils.h oglwidget.h Parsing/Parser.h Parsing/ParserAlt.h Parsing/Lexer.h Utils/StringUtils.h VectorField.h Graphics/Number.h $(DISTDIR)/
	$(COPY_FILE) --parents Expr.cpp main.cpp mainwidget.cpp Utils/MathUtils.cpp oglwidget.cpp Parsing/Parser.cpp Parsing/ParserAlt.cpp Parsing/Lexer.cpp Utils/StringUtils.cpp VectorField.cpp Graphics/Number.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r Vector\ Visualizer.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)"

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../../../Qt/6.0.2/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -O2 -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk -mmacosx-version-min=10.14 -Wall -Wextra -dM -E -o moc_predefs.h ../../../../Qt/6.0.2/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwidget.cpp
moc_mainwidget.cpp: mainwidget.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/QtWidgets \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qtwidgetsglobal.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qabstractbutton.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qabstractitemdelegate.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qabstractitemview.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qabstractscrollarea.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qabstractslider.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qabstractspinbox.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qaccessiblewidget.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qaction.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qactiongroup.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qbuttongroup.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qcalendarwidget.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qcheckbox.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qcolordialog.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qcolormap.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qcolumnview.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qcombobox.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qcommandlinkbutton.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qcommonstyle.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qcompleter.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qdatawidgetmapper.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qdatetimeedit.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qdial.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qdialogbuttonbox.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qdockwidget.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qdrawutil.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qerrormessage.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qfileiconprovider.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qfilesystemmodel.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qfocusframe.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qfontcombobox.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qfontdialog.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qformlayout.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qframe.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qgesture.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qgesturerecognizer.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qgraphicsanchorlayout.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qgraphicseffect.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qgraphicsgridlayout.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitemanimation.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qgraphicslayout.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qgraphicslayoutitem.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qgraphicslinearlayout.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qgraphicsproxywidget.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qgraphicssceneevent.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qgraphicstransform.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qgraphicswidget.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qgridlayout.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qgroupbox.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qheaderview.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qinputdialog.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qitemdelegate.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qitemeditorfactory.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qkeysequenceedit.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qlayout.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qlayoutitem.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qlcdnumber.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qlistview.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qlistwidget.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qmdiarea.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qmdisubwindow.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qmenu.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qmenubar.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qplaintextedit.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qprogressbar.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qprogressdialog.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qproxystyle.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qradiobutton.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qrubberband.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qscrollarea.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qscrollbar.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qscroller.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qscrollerproperties.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qshortcut.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qsizegrip.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qsizepolicy.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qslider.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qspinbox.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qsplashscreen.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qsplitter.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qstackedlayout.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qstackedwidget.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qstatusbar.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qstyle.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qstyleditemdelegate.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qstylefactory.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qstyleoption.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qstylepainter.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qstyleplugin.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qsystemtrayicon.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qtabbar.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qtableview.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qtablewidget.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qtabwidget.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qtextbrowser.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qtextedit.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qtoolbar.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qtoolbox.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qtoolbutton.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qtooltip.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qtreeview.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qtreewidget.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qtreewidgetitemiterator.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qundogroup.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qundostack.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qundoview.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qwhatsthis.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qwidgetaction.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qwizard.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qtwidgetsversion.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/QMenuBar \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/QLineEdit \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/QTabWidget \
		../../../../Qt/6.0.2/clang_64/lib/QtCore.framework/Headers/QEvent \
		../../../../Qt/6.0.2/clang_64/lib/QtCore.framework/Headers/qcoreevent.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/QDoubleSpinBox \
		oglwidget.h \
		../../../../Qt/6.0.2/clang_64/lib/QtOpenGLWidgets.framework/Headers/QOpenGLWidget \
		../../../../Qt/6.0.2/clang_64/lib/QtOpenGLWidgets.framework/Headers/qopenglwidget.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/QTextBrowser \
		../../../../Qt/6.0.2/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../../../Qt/6.0.2/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../../../../Qt/6.0.2/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../../../Qt/6.0.2/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../../Qt/6.0.2/clang_64/lib/QtGui.framework/Headers/QWheelEvent \
		Utils/MathUtils.h \
		Expr.h \
		VectorField.h \
		Utils/StringUtils.h \
		../../../../Qt/6.0.2/clang_64/lib/QtCore.framework/Headers/QString \
		../../../../Qt/6.0.2/clang_64/lib/QtCore.framework/Headers/qstring.h \
		Graphics/Number.h \
		moc_predefs.h \
		../../../../Qt/6.0.2/clang_64/bin/moc
	/Users/KKjeer/Qt/6.0.2/clang_64/bin/moc $(DEFINES) --include '/Users/KKjeer/Documents/Coding/Qt/Vector Visualizer/moc_predefs.h' -I/Users/KKjeer/Qt/6.0.2/clang_64/mkspecs/macx-clang -I'/Users/KKjeer/Documents/Coding/Qt/Vector Visualizer' -I'/Users/KKjeer/Documents/Coding/Qt/Vector Visualizer' -I/Users/KKjeer/Qt/6.0.2/clang_64/lib/QtOpenGLWidgets.framework/Headers -I/Users/KKjeer/Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers -I/Users/KKjeer/Qt/6.0.2/clang_64/lib/QtOpenGL.framework/Headers -I/Users/KKjeer/Qt/6.0.2/clang_64/lib/QtGui.framework/Headers -I/Users/KKjeer/Qt/6.0.2/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.5/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/KKjeer/Qt/6.0.2/clang_64/lib mainwidget.h -o moc_mainwidget.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

Expr.o: Expr.cpp Expr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Expr.o Expr.cpp

main.o: main.cpp ../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/QtWidgets \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qtwidgetsglobal.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qabstractbutton.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qabstractitemdelegate.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qabstractitemview.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qabstractscrollarea.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qabstractslider.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qabstractspinbox.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qaccessiblewidget.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qaction.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qactiongroup.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qbuttongroup.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qcalendarwidget.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qcheckbox.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qcolordialog.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qcolormap.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qcolumnview.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qcombobox.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qcommandlinkbutton.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qcommonstyle.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qcompleter.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qdatawidgetmapper.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qdatetimeedit.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qdial.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qdialogbuttonbox.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qdockwidget.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qdrawutil.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qerrormessage.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qfileiconprovider.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qfilesystemmodel.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qfocusframe.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qfontcombobox.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qfontdialog.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qformlayout.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qframe.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qgesture.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qgesturerecognizer.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qgraphicsanchorlayout.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qgraphicseffect.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qgraphicsgridlayout.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitemanimation.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qgraphicslayout.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qgraphicslayoutitem.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qgraphicslinearlayout.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qgraphicsproxywidget.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qgraphicssceneevent.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qgraphicstransform.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qgraphicswidget.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qgridlayout.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qgroupbox.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qheaderview.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qinputdialog.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qitemdelegate.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qitemeditorfactory.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qkeysequenceedit.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qlayout.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qlayoutitem.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qlcdnumber.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qlistview.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qlistwidget.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qmdiarea.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qmdisubwindow.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qmenu.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qmenubar.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qplaintextedit.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qprogressbar.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qprogressdialog.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qproxystyle.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qradiobutton.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qrubberband.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qscrollarea.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qscrollbar.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qscroller.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qscrollerproperties.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qshortcut.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qsizegrip.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qsizepolicy.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qslider.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qspinbox.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qsplashscreen.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qsplitter.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qstackedlayout.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qstackedwidget.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qstatusbar.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qstyle.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qstyleditemdelegate.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qstylefactory.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qstyleoption.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qstylepainter.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qstyleplugin.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qsystemtrayicon.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qtabbar.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qtableview.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qtablewidget.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qtabwidget.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qtextbrowser.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qtextedit.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qtoolbar.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qtoolbox.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qtoolbutton.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qtooltip.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qtreeview.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qtreewidget.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qtreewidgetitemiterator.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qundogroup.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qundostack.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qundoview.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qwhatsthis.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qwidgetaction.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qwizard.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qtwidgetsversion.h \
		mainwidget.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/QMenuBar \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/QLineEdit \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/QTabWidget \
		../../../../Qt/6.0.2/clang_64/lib/QtCore.framework/Headers/QEvent \
		../../../../Qt/6.0.2/clang_64/lib/QtCore.framework/Headers/qcoreevent.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/QDoubleSpinBox \
		oglwidget.h \
		../../../../Qt/6.0.2/clang_64/lib/QtOpenGLWidgets.framework/Headers/QOpenGLWidget \
		../../../../Qt/6.0.2/clang_64/lib/QtOpenGLWidgets.framework/Headers/qopenglwidget.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/QTextBrowser \
		../../../../Qt/6.0.2/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../../../Qt/6.0.2/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../../../../Qt/6.0.2/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../../../Qt/6.0.2/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../../Qt/6.0.2/clang_64/lib/QtGui.framework/Headers/QWheelEvent \
		Utils/MathUtils.h \
		Expr.h \
		VectorField.h \
		Utils/StringUtils.h \
		../../../../Qt/6.0.2/clang_64/lib/QtCore.framework/Headers/QString \
		../../../../Qt/6.0.2/clang_64/lib/QtCore.framework/Headers/qstring.h \
		Graphics/Number.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwidget.o: mainwidget.cpp ../../../../Qt/6.0.2/clang_64/lib/QtGui.framework/Headers/QKeySequence \
		../../../../Qt/6.0.2/clang_64/lib/QtGui.framework/Headers/qkeysequence.h \
		mainwidget.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/QtWidgets \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qtwidgetsglobal.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qabstractbutton.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qabstractitemdelegate.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qabstractitemview.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qabstractscrollarea.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qabstractslider.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qabstractspinbox.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qaccessiblewidget.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qaction.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qactiongroup.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qbuttongroup.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qcalendarwidget.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qcheckbox.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qcolordialog.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qcolormap.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qcolumnview.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qcombobox.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qcommandlinkbutton.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qcommonstyle.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qcompleter.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qdatawidgetmapper.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qdatetimeedit.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qdial.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qdialogbuttonbox.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qdockwidget.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qdrawutil.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qerrormessage.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qfileiconprovider.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qfilesystemmodel.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qfocusframe.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qfontcombobox.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qfontdialog.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qformlayout.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qframe.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qgesture.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qgesturerecognizer.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qgraphicsanchorlayout.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qgraphicseffect.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qgraphicsgridlayout.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitemanimation.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qgraphicslayout.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qgraphicslayoutitem.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qgraphicslinearlayout.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qgraphicsproxywidget.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qgraphicssceneevent.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qgraphicstransform.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qgraphicswidget.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qgridlayout.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qgroupbox.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qheaderview.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qinputdialog.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qitemdelegate.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qitemeditorfactory.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qkeysequenceedit.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qlayout.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qlayoutitem.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qlcdnumber.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qlistview.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qlistwidget.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qmdiarea.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qmdisubwindow.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qmenu.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qmenubar.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qplaintextedit.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qprogressbar.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qprogressdialog.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qproxystyle.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qradiobutton.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qrubberband.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qscrollarea.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qscrollbar.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qscroller.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qscrollerproperties.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qshortcut.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qsizegrip.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qsizepolicy.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qslider.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qspinbox.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qsplashscreen.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qsplitter.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qstackedlayout.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qstackedwidget.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qstatusbar.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qstyle.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qstyleditemdelegate.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qstylefactory.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qstyleoption.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qstylepainter.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qstyleplugin.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qsystemtrayicon.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qtabbar.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qtableview.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qtablewidget.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qtabwidget.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qtextbrowser.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qtextedit.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qtoolbar.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qtoolbox.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qtoolbutton.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qtooltip.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qtreeview.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qtreewidget.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qtreewidgetitemiterator.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qundogroup.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qundostack.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qundoview.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qwhatsthis.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qwidgetaction.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qwizard.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qtwidgetsversion.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/QMenuBar \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/QLineEdit \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/QTabWidget \
		../../../../Qt/6.0.2/clang_64/lib/QtCore.framework/Headers/QEvent \
		../../../../Qt/6.0.2/clang_64/lib/QtCore.framework/Headers/qcoreevent.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/QDoubleSpinBox \
		oglwidget.h \
		../../../../Qt/6.0.2/clang_64/lib/QtOpenGLWidgets.framework/Headers/QOpenGLWidget \
		../../../../Qt/6.0.2/clang_64/lib/QtOpenGLWidgets.framework/Headers/qopenglwidget.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/QTextBrowser \
		../../../../Qt/6.0.2/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../../../Qt/6.0.2/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../../../../Qt/6.0.2/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../../../Qt/6.0.2/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../../Qt/6.0.2/clang_64/lib/QtGui.framework/Headers/QWheelEvent \
		Utils/MathUtils.h \
		Expr.h \
		VectorField.h \
		Utils/StringUtils.h \
		../../../../Qt/6.0.2/clang_64/lib/QtCore.framework/Headers/QString \
		../../../../Qt/6.0.2/clang_64/lib/QtCore.framework/Headers/qstring.h \
		Graphics/Number.h \
		Parsing/Parser.h \
		Parsing/Lexer.h \
		Parsing/ParserAlt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwidget.o mainwidget.cpp

MathUtils.o: Utils/MathUtils.cpp Utils/MathUtils.h \
		Expr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MathUtils.o Utils/MathUtils.cpp

oglwidget.o: oglwidget.cpp oglwidget.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../../Qt/6.0.2/clang_64/lib/QtOpenGLWidgets.framework/Headers/QOpenGLWidget \
		../../../../Qt/6.0.2/clang_64/lib/QtOpenGLWidgets.framework/Headers/qopenglwidget.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/QTextBrowser \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qtextbrowser.h \
		../../../../Qt/6.0.2/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../../../Qt/6.0.2/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../../../../Qt/6.0.2/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../../../Qt/6.0.2/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../../Qt/6.0.2/clang_64/lib/QtGui.framework/Headers/QWheelEvent \
		Utils/MathUtils.h \
		Expr.h \
		VectorField.h \
		Utils/StringUtils.h \
		../../../../Qt/6.0.2/clang_64/lib/QtCore.framework/Headers/QString \
		../../../../Qt/6.0.2/clang_64/lib/QtCore.framework/Headers/qstring.h \
		Graphics/Number.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o oglwidget.o oglwidget.cpp

Parser.o: Parsing/Parser.cpp Parsing/Parser.h \
		Expr.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/QTextBrowser \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qtextbrowser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Parser.o Parsing/Parser.cpp

ParserAlt.o: Parsing/ParserAlt.cpp Parsing/ParserAlt.h \
		Expr.h \
		Parsing/Lexer.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/QTextBrowser \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qtextbrowser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ParserAlt.o Parsing/ParserAlt.cpp

Lexer.o: Parsing/Lexer.cpp Parsing/Lexer.h \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/QTextBrowser \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Headers/qtextbrowser.h \
		Expr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Lexer.o Parsing/Lexer.cpp

StringUtils.o: Utils/StringUtils.cpp Utils/StringUtils.h \
		../../../../Qt/6.0.2/clang_64/lib/QtCore.framework/Headers/QString \
		../../../../Qt/6.0.2/clang_64/lib/QtCore.framework/Headers/qstring.h \
		Utils/MathUtils.h \
		Expr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o StringUtils.o Utils/StringUtils.cpp

VectorField.o: VectorField.cpp VectorField.h \
		Expr.h \
		Utils/MathUtils.h \
		Utils/StringUtils.h \
		../../../../Qt/6.0.2/clang_64/lib/QtCore.framework/Headers/QString \
		../../../../Qt/6.0.2/clang_64/lib/QtCore.framework/Headers/qstring.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o VectorField.o VectorField.cpp

Number.o: Graphics/Number.cpp Graphics/Number.h \
		Utils/MathUtils.h \
		Expr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Number.o Graphics/Number.cpp

moc_mainwidget.o: moc_mainwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwidget.o moc_mainwidget.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

