#############################################################################
# Makefile for building: Vector\ Visualizer.app/Contents/MacOS/Vector\ Visualizer
# Generated by qmake (3.1) (Qt 6.0.2)
# Project:  Vector Visualizer.pro
# Template: app
# Command: /Users/KKjeer/Qt/6.0.2/clang_64/bin/qmake -o Vector\ Visualizer.xcodeproj/project.pbxproj Vector\ Visualizer.pro -spec macx-xcode
#############################################################################

MAKEFILE      = project.pbxproj

EQ            = =

QMAKE    = /Users/KKjeer/Qt/6.0.2/clang_64/bin/qmake
Vector\ Visualizer.xcodeproj/project.pbxproj: Vector\ Visualizer.pro ../../../../Qt/6.0.2/clang_64/mkspecs/macx-clang/qmake.conf ../../../../Qt/6.0.2/clang_64/mkspecs/features/spec_pre.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/device_config.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/common/unix.conf \
		../../../../Qt/6.0.2/clang_64/mkspecs/common/mac.conf \
		../../../../Qt/6.0.2/clang_64/mkspecs/common/macx.conf \
		../../../../Qt/6.0.2/clang_64/mkspecs/common/sanitize.conf \
		../../../../Qt/6.0.2/clang_64/mkspecs/common/gcc-base.conf \
		../../../../Qt/6.0.2/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../../Qt/6.0.2/clang_64/mkspecs/common/clang.conf \
		../../../../Qt/6.0.2/clang_64/mkspecs/common/clang-mac.conf \
		../../../../Qt/6.0.2/clang_64/mkspecs/qconfig.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_ext_freetype.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_ext_libpng.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_core_qobject_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_linguist.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_linguist_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_openglwidgets.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_svgwidgets.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_tools_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/qt_functions.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/qt_config.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../../Qt/6.0.2/clang_64/mkspecs/macx-xcode/qmake.conf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/toolchain.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/mac/toolchain.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/default_pre.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/resolve_config.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/default_post.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/mac/mac.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/warn_on.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/qt.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/resources_functions.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/resources.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/moc.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/unix/opengl.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/uic.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/unix/thread.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/qmake_use.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/file_copies.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/mac/rez.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/exceptions.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/yacc.prf \
		../../../../Qt/6.0.2/clang_64/mkspecs/features/lex.prf \
		Vector\ Visualizer.pro \
		../../../../Qt/6.0.2/clang_64/lib/QtOpenGLWidgets.framework/Resources/QtOpenGLWidgets.prl \
		../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		../../../../Qt/6.0.2/clang_64/lib/QtOpenGL.framework/Resources/QtOpenGL.prl \
		../../../../Qt/6.0.2/clang_64/lib/QtGui.framework/Resources/QtGui.prl \
		../../../../Qt/6.0.2/clang_64/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Vector\ Visualizer.xcodeproj/project.pbxproj Vector\ Visualizer.pro -spec macx-xcode
	@echo 'warning: Xcode project has been regenerated, custom settings have been lost. Use CONFIG+=no_autoqmake to prevent this behavior in the future, at the cost of requiring manual project change tracking.'
../../../../Qt/6.0.2/clang_64/mkspecs/features/spec_pre.prf:
../../../../Qt/6.0.2/clang_64/mkspecs/features/device_config.prf:
../../../../Qt/6.0.2/clang_64/mkspecs/common/unix.conf:
../../../../Qt/6.0.2/clang_64/mkspecs/common/mac.conf:
../../../../Qt/6.0.2/clang_64/mkspecs/common/macx.conf:
../../../../Qt/6.0.2/clang_64/mkspecs/common/sanitize.conf:
../../../../Qt/6.0.2/clang_64/mkspecs/common/gcc-base.conf:
../../../../Qt/6.0.2/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../../Qt/6.0.2/clang_64/mkspecs/common/clang.conf:
../../../../Qt/6.0.2/clang_64/mkspecs/common/clang-mac.conf:
../../../../Qt/6.0.2/clang_64/mkspecs/qconfig.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_ext_freetype.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_ext_libpng.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_core_qobject_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_linguist.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_linguist_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_openglwidgets.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_openglwidgets_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_qmlmodels.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_svgwidgets.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_svgwidgets_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_tools_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../../Qt/6.0.2/clang_64/mkspecs/features/qt_functions.prf:
../../../../Qt/6.0.2/clang_64/mkspecs/features/qt_config.prf:
../../../../Qt/6.0.2/clang_64/mkspecs/macx-clang/qmake.conf:
../../../../Qt/6.0.2/clang_64/mkspecs/macx-xcode/qmake.conf:
../../../../Qt/6.0.2/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../../Qt/6.0.2/clang_64/mkspecs/features/exclusive_builds.prf:
../../../../Qt/6.0.2/clang_64/mkspecs/features/mac/sdk.prf:
../../../../Qt/6.0.2/clang_64/mkspecs/features/toolchain.prf:
../../../../Qt/6.0.2/clang_64/mkspecs/features/mac/toolchain.prf:
../../../../Qt/6.0.2/clang_64/mkspecs/features/default_pre.prf:
../../../../Qt/6.0.2/clang_64/mkspecs/features/mac/default_pre.prf:
../../../../Qt/6.0.2/clang_64/mkspecs/features/resolve_config.prf:
../../../../Qt/6.0.2/clang_64/mkspecs/features/default_post.prf:
../../../../Qt/6.0.2/clang_64/mkspecs/features/mac/default_post.prf:
../../../../Qt/6.0.2/clang_64/mkspecs/features/mac/objective_c.prf:
../../../../Qt/6.0.2/clang_64/mkspecs/features/mac/mac.prf:
../../../../Qt/6.0.2/clang_64/mkspecs/features/warn_on.prf:
../../../../Qt/6.0.2/clang_64/mkspecs/features/qt.prf:
../../../../Qt/6.0.2/clang_64/mkspecs/features/resources_functions.prf:
../../../../Qt/6.0.2/clang_64/mkspecs/features/resources.prf:
../../../../Qt/6.0.2/clang_64/mkspecs/features/moc.prf:
../../../../Qt/6.0.2/clang_64/mkspecs/features/unix/opengl.prf:
../../../../Qt/6.0.2/clang_64/mkspecs/features/uic.prf:
../../../../Qt/6.0.2/clang_64/mkspecs/features/unix/thread.prf:
../../../../Qt/6.0.2/clang_64/mkspecs/features/qmake_use.prf:
../../../../Qt/6.0.2/clang_64/mkspecs/features/file_copies.prf:
../../../../Qt/6.0.2/clang_64/mkspecs/features/mac/rez.prf:
../../../../Qt/6.0.2/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../../../../Qt/6.0.2/clang_64/mkspecs/features/testcase_targets.prf:
../../../../Qt/6.0.2/clang_64/mkspecs/features/exceptions.prf:
../../../../Qt/6.0.2/clang_64/mkspecs/features/yacc.prf:
../../../../Qt/6.0.2/clang_64/mkspecs/features/lex.prf:
Vector\ Visualizer.pro:
../../../../Qt/6.0.2/clang_64/lib/QtOpenGLWidgets.framework/Resources/QtOpenGLWidgets.prl:
../../../../Qt/6.0.2/clang_64/lib/QtWidgets.framework/Resources/QtWidgets.prl:
../../../../Qt/6.0.2/clang_64/lib/QtOpenGL.framework/Resources/QtOpenGL.prl:
../../../../Qt/6.0.2/clang_64/lib/QtGui.framework/Resources/QtGui.prl:
../../../../Qt/6.0.2/clang_64/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Vector\ Visualizer.xcodeproj/project.pbxproj Vector\ Visualizer.pro -spec macx-xcode

qmake_all: FORCE

